### ISSUE TITLE
Błąd podczas ładowania obrazków

### ISSUE THREAD

**Issue by krzysdz** [Szarp/Kolko#1]
Nie ładują się obrazki, bo nie istnieje plik "owoc.png".

**Comment by krzysdz** [comment]
![a](https://cloud.githubusercontent.com/assets/12915102/8214699/3ea3e656-152b-11e5-807b-8d27518609f7.JPG)

**Comment by Szarp** [comment]
wiesz kiedy ja to osatni raz uruchamiałem i potrzebowałem tego? :)

**Comment by krzysdz** [comment]
Ale mogłeś chociaż zrobić bez błędów.
